version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      redis_network:

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CONFIG=src/configs/docker-config.yaml
    networks:
      redis_network:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: proxy-server
    ports:
      - "8001:8001"
    networks:
      redis_network:
    restart: always
    depends_on:
      - app

networks:
  redis_network: