version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - main_network

  app:
    build:
      context: ./app
    container_name: fast_api_server
    depends_on:
      - redis
    restart: always
    environment:
      - CONFIG=app/configs/docker-config.yaml
    networks:
      - main_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: proxy_server
    ports:
      - "8000:8000"
    networks:
      - main_network
    restart: always
    depends_on:
      - app

networks:
  main_network:
