version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      redis_network:

  app:
    build:
      context: .
    container_name: fastapi_server
    ports:
      - 8000:8000
    #    environment:
    #      - AA_REDIS__HOST=redis
    depends_on:
      - redis
    restart: always
    networks:
      redis_network:

networks:
  redis_network: