app:
  name: 'Statistic vendor for widgets'
  description: 'Backend for statistic vendor'
  debug: false
  version: '0.0.1'
  env: 'local'

server:
  docs_url: '/docs'
  openapi_url: '/openapi.json'
  host: fast_api_server
  port: 8001
  workers: 1

redis:
  host: 'redis'
  port: 6379
  db: 5
