app:
    name: 'Statistic vendor for widgets'
    description: 'Backend for statistic vendor'
    debug: true
    version: '0.0.1'
    env: 'local'

server:
    docs_url: '/docs'
    openapi_url: '/openapi.json'
    root_path: 'http://127.0.0.1:8000'
    host: '127.0.0.1'
    port: 8000
    workers: 1