app:
  name: 'Statistic vendor for widgets'
  description: 'Backend for statistic vendor'
  debug: true
  version: '0.0.1'
  env: 'local'

server:
  docs_url: '/docs'
  openapi_url: '/openapi.json'
  host: '0.0.0.0'
  port: 8000
  workers: 1

redis:
  host: 'redis'
  port: 6379
  db: 1
