app:
  name: 'Statistics provider service'
  description: 'Backend for statistics provider service'
  debug: false
  version: '0.0.1'
  env: 'local'

server:
  docs_url: '/docs'
  openapi_url: '/openapi.json'
  host: 127.0.0.1
  port: 8000
  workers: 1

redis:
  host: 'redis'
  port: 6379
  db: 3
